# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu', models.TextField(null=True)),
                ('type', models.CharField(max_length=100)),
                ('etat', models.BooleanField()),
            ],
        ),
    ]
