# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='nom',
            new_name='titre',
        ),
    ]
