# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160617_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='titre',
            new_name='nom',
        ),
    ]
