# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160617_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Sport',
        ),
        migrations.RenameField(
            model_name='terrain',
            old_name='type',
            new_name='sport',
        ),
    ]
